name: Print user name
on: 
    workflow_dispatch:
        inputs:
            username:
                description: "Please enter your username"
                required: true

jobs:
  show-usernames:
    runs-on: ubuntu-latest
    steps:
      - name: Print entered username
        run: echo "username entered: ${{ github.event.inputs.username }}"
